language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
  - common/node_modules
  - backend/node_modules
  - backend/.cache
  - backend/dist
  - frontend/node_modules
  - frontend/.cache
  - frontend/dist
install:
- cd common && yarn install
- cd ../backend && yarn install
- cd ../frontend && yarn install
- cd .. && yarn install
script:
- cd backend && yarn build
- cd ../frontend && yarn build
- cd .. && yarn eslint
